// The Notes tab: views, agenda groups, reading a heading and a roam note
// (id links), read aloud, search (notes + memory), capture, and the setup
// checklist with a watched window. Mock only: a real capture writes David's
// inbox, and a real say makes his phone talk.
import { chromium, SHOTS } from './lib.mjs'
const BASE = process.env.BASE || 'http://127.0.0.1:8811'
let fails = 0
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) fails++ }
const mock = async (qs = '') => (await fetch(BASE + '/mock/notes' + qs)).json()
await fetch(BASE + '/mock/delay?ms=0')
await mock('?reset=1')
await fetch(BASE + '/mock/pair')
const pr = await (await fetch(BASE + '/pair', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: 'c0ffee42' }) })).json()
const b = await chromium.launch()
const page = await (await b.newContext({ viewport: { width: 390, height: 780 }, isMobile: true, hasTouch: true })).newPage()
await page.route('**/input', (r) => r.abort())
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
await page.goto(BASE + '/settings')
await page.evaluate(([base, res]) => { localStorage.setItem('sasonica.chat.baseUrl', base); localStorage.setItem('sasonica.chat.device', JSON.stringify({ token: res.token, device_id: res.device_id, name: 't', server: res.server, pairedAt: Date.now() })); localStorage.removeItem('sasonica.notes.view') }, [BASE, pr])

// 0. Home: the Agenda section — overdue and today, tickable, and the way in
await page.goto(BASE + '/')
await page.waitForSelector('.dash-agenda .note-row')
const homeRows = await page.locator('.dash-agenda .note-row .title').allInnerTexts()
ok(homeRows.includes('Water the fern') && homeRows.includes('Renew the passport') && !homeRows.includes('Ring the plumber'), `Home agenda: overdue and today only (${homeRows.join(', ')})`)
ok((await page.locator('.dash-agenda .dash-count').innerText()) === String(homeRows.length), 'the count matches')
ok((await page.locator('a[title="Notes"], .bar a[href="/organiser"]').count()) === 0, 'no ✎ icon in the header any more')
await page.screenshot({ path: SHOTS + '/notes-00-home.png' })
await page.click('.dash-agenda button[aria-label="Mark done: Renew the passport"]')
await page.waitForSelector('.dash-agenda .note-toast:has-text("Done: Renew the passport")')
ok(!(await page.locator('.dash-agenda').innerText()).includes('Renew the passport\ntoday'), 'ticked on Home')
await page.click('.dash-agenda .note-toast button:has-text("Undo")')
await page.waitForSelector('.dash-agenda .note-row:has-text("Renew the passport")')
ok(true, 'Undo on Home brings it back')

// 1. Home → Organiser (the link, then the tabs); the agenda first, grouped by day
await page.click('.dash-agenda a.open-organiser')
await page.waitForURL(BASE + '/organiser')
ok((await page.locator('.tabs .tab.on').innerText()) === 'Organiser', 'the Organiser tab is on')
await page.click('.tabs .tab:has-text("Threads")')
await page.waitForURL(BASE + '/threads')
await page.click('.tabs .tab:has-text("Organiser")')
await page.waitForURL(BASE + '/organiser')
await page.goBack()
await page.waitForURL(BASE + '/')
ok(true, 'Home → Organiser → Threads → Organiser, and back is Home')
await page.click('.tabs .tab:has-text("Organiser")')
await page.waitForSelector('.agenda-day')
const days = await page.locator('.agenda-day h2').allTextContents()
ok(days[0] === 'Overdue' && days.includes('Today') && days.includes('Tomorrow'), `agenda groups: ${days.join(', ')}`)
ok((await page.locator('.agenda-day').first().innerText()).includes('Water the fern'), 'the overdue fern is under Overdue')
await page.screenshot({ path: SHOTS + '/notes-01-agenda.png' })

// 2. The inbox: sections and states, DONE left out; remembered across a reload
await page.click('.note-view:has-text("Inbox")')
await page.waitForSelector('.note-section')
const inbox = await page.locator('.note-list').innerText()
ok(inbox.includes('THIS WEEK') && inbox.includes('Ring the plumber') && !inbox.includes('Posted the parcel'), 'inbox: sections, open items, no DONE')
ok((await page.locator('.note-view.on .count').innerText()) === '3', 'the Inbox chip counts 3 open')
await page.reload()
await page.waitForSelector('.note-section')
ok((await page.locator('.note-view.on').innerText()).startsWith('Inbox'), 'the chosen view is remembered')

// 3. A heading opens as its subtree, with state and date; read aloud
await page.click('.note-row:has-text("Ring the plumber")')
await page.waitForSelector('.note-body')
ok((await page.locator('.bar h1').innerText()).includes('NEXT') && (await page.locator('.bar h1').innerText()).includes('Ring the plumber'), 'title shows the state and heading')
ok((await page.locator('.org-date').innerText()).startsWith('DEADLINE'), 'the deadline line is shown')
ok(!(await page.locator('.note-body').innerText()).includes('Library hold'), 'only that subtree')
await page.click('button[title="Read aloud"]')
await page.waitForSelector('.notice:has-text("Reading it out")')
const said = (await mock()).said
ok(said.length === 1 && said[0].path === 'inbox.org' && said[0].at > 0, `POST /notes/say {path, at} (${JSON.stringify(said)})`)
await page.screenshot({ path: SHOTS + '/notes-02-heading.png' })

// 3b. The chat box at its foot: a fresh session about this item, then listed on the item
const noteUrl = page.url()
ok((await page.locator('.note-ask .input').getAttribute('placeholder')) === 'Ask about this…', 'a chat box under the heading')
await page.fill('.note-ask .input', 'who was the last plumber?')
await page.keyboard.press('Enter')
ok((await page.locator('.note-ask .input').inputValue()) === 'who was the last plumber?\n', 'Enter is a new line, not a send')
await page.screenshot({ path: SHOTS + '/notes-02b-ask.png' })
await page.keyboard.press('Control+Enter')
await page.waitForURL(/\/t\//)
const asked = (await mock()).asked
ok(asked.length === 1 && asked[0].path === 'inbox.org' && asked[0].prompt.startsWith('About "Ring the plumber" in my Org notes (~/org/inbox.org, line ') && asked[0].prompt.endsWith(', NEXT): who was the last plumber?'), `POST /notes/ask names the item (${asked[0]?.prompt})`)
await page.goto(noteUrl)
await page.waitForSelector('.note-chats a')
ok((await page.locator('.note-chats a').innerText()).includes('who was the last plumber?'), 'the chat is listed on the item')
ok((await page.locator('.note-ask .input').inputValue()) === '', 'the box is empty after the send')
await page.click('.note-chats a')
await page.waitForURL(/\/t\//)
ok(page.url().includes(encodeURIComponent(asked[0].session)), 'the chip opens that thread')
await page.goBack()

// 4. A roam note: markup, checkboxes, and an id link that opens the other note
await page.goto(BASE + '/organiser')
await page.click('.note-view:has-text("Project notes")')
await page.click('.note-row:has-text("Garden plan")')
await page.waitForSelector('.note-body')
const body = await page.locator('.note-body').innerText()
ok(!body.includes(':PROPERTIES:') && !body.includes('#+title'), 'drawers and keywords hidden')
ok((await page.locator('.org-check').count()) === 2 && (await page.locator('.note-body em').innerText()) === 'beans', 'checkboxes and /italic/')
await page.screenshot({ path: SHOTS + '/notes-03-roam.png' })
await page.locator('.note-body p a:has-text("seed list")').click()
await page.waitForSelector('.bar h1:has-text("Seed list")')
ok(true, 'the id link opened Seed list')

// 5. Search: notes and memory; agent notes only when asked
await page.goto(BASE + '/organiser')
await page.click('button[title="Search"]')
await page.fill('.search-box input[type=search]', 'fern')
await page.waitForSelector('.memory-hit')
ok((await page.locator('.note-hit').count()) === 1, 'one note hit (the session note left out)')
ok((await page.locator('.memory-hit').innerText()).includes('repotted'), 'a memory hit beside it')
await page.check('.search-all input')
await page.waitForFunction(() => document.querySelectorAll('.note-hit').length === 2)
ok(true, 'agent notes too: two hits')
await page.screenshot({ path: SHOTS + '/notes-04-search.png' })
await page.click('button[title="Close search"]')

// 6. Capture: a to-do, then a note; the inbox list refreshes
await page.click('.note-view:has-text("Inbox")')
await page.waitForSelector('.note-section')
ok(await page.locator('.capture button[type=submit]').isDisabled(), 'Save disabled while empty')
await page.fill('.capture textarea', 'Buy stakes for the beans')
await page.click('.capture button[type=submit]')
await page.waitForSelector('.capture-note:has-text("Added to the inbox")')
await page.waitForSelector('.note-row:has-text("Buy stakes")')
ok((await page.locator('.capture textarea').inputValue()) === '', 'the box clears')
await page.click('.capture-kind button:has-text("Note")')
await page.fill('.capture textarea', 'Fence posts are 1.8 m')
await page.keyboard.press('Control+Enter')
await page.waitForSelector('.capture-note:has-text("Noted in the inbox")')
const log = await mock()
ok(log.captures.length === 2 && log.captures[0].kind === 'todo' && log.captures[1].kind === 'note', 'POST /notes/capture twice, todo then note')
ok((await page.locator('.note-row:has-text("Fence posts")').count()) === 1 && (await page.locator('.note-section:has-text("Fence posts")').count()) === 0, 'a captured note is a row, not a section')
ok(log.inbox.includes('* TODO Buy stakes for the beans') && log.inbox.includes('\n* Fence posts are 1.8 m'), 'appended to inbox.org')
await page.screenshot({ path: SHOTS + '/notes-05-capture.png' })

// 7. A server with no notes: the empty state leads to setup; create; then a watched install
await mock('?unset=1')
await page.goto(BASE + '/organiser')
await page.waitForSelector('.notes-empty')
ok((await page.locator('.capture').count()) === 0, 'no capture box without notes')
await page.click('.notes-empty a')
await page.waitForSelector('.setup-item')
ok((await page.locator('.setup-item.missing').count()) === 2, 'folder and paragtd missing')
await page.screenshot({ path: SHOTS + '/notes-06-setup.png' })
await page.click('.setup-item:has-text("Notes folder") button:has-text("Start fresh notes")')
await page.waitForSelector('.notice:has-text("Created inbox.org")')
await page.waitForSelector('.setup-item.ok:has-text("Notes folder")')
ok(true, 'create → the folder is ready')
await page.click('.setup-item:has-text("paragtd") button:has-text("Install")')
await page.waitForSelector('.setup-window')
await page.fill('.setup-type input', 'y')
await page.click('.setup-type button[type=submit]')
await page.waitForSelector('.setup-exit.ok', { timeout: 10000 })
ok((await page.locator('.setup-screen').innerText()).includes('bootstrap ok'), 'the window screen is polled to the end')
await page.screenshot({ path: SHOTS + '/notes-07-window.png' })
await page.click('.setup-window-head button:has-text("Done")')
await page.waitForSelector('.setup-window', { state: 'detached' })
const keys = (await mock()).keys
ok(keys[0]?.path === '/harnesses/keys' && keys[0].text === 'y' && keys[0].key === 'Enter' && keys[1]?.path === '/harnesses/close', `typed y + Enter, then closed (${JSON.stringify(keys)})`)
await page.click('.bar a[title="Organiser"]')
await page.waitForSelector('.note-views')
ok(true, 'back to a working Notes tab')

// 8. Landscape and Larger text still fit
await page.setViewportSize({ width: 915, height: 412 })
await page.evaluate(() => document.documentElement.style.setProperty('--text-size', '21px'))
await page.goto(BASE + '/organiser')
await page.waitForSelector('.note-views')
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
ok(!overflow, 'no sideways scroll in landscape at Larger text')
await page.screenshot({ path: SHOTS + '/notes-08-landscape.png' })

ok(errors.length === 0, `no page errors${errors.length ? ': ' + errors.join('; ') : ''}`)
await mock('?reset=1')
await b.close()
console.log(fails ? `${fails} FAILED` : 'all passed')
process.exit(fails ? 1 : 0)
